spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 3
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.orm.jpa:
      JpaTransactionManager: DEBUG
    org.hibernate:
      SQL: DEBUG
      stat: DEBUG
      cache: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

