spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 3
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
logging:
  level:
    org.springframework.orm.jpa:
      JpaTransactionManager: DEBUG
    org.hibernate:
      SQL: DEBUG
      stat: DEBUG
      cache: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    liquibase: INFO